market_research:
  description: >
    Investigue as últimas tendências, hashtags e atividades de concorrentes no Instagram específicas para a indústria desta conta do Instagram. Concentre-se em coletar dados que revelem o que conteúdo tem bom desempenho no ano atual, identificando padrões, preferências e tendências emergentes.

    Data atual: {current_date}

    Descrição da conta do instagram para a qual você está fazendo esta pesquisa:
    <INSTAGRAM_ACCOUNT_DESCRIPTION>{instagram_description}</INSTAGRAM_ACCOUNT_DESCRIPTION>

    Encontre os tópicos mais relevantes, hashtags e tendências para usar nas postagens da próxima semana.
    O foco da semana seguinte é o seguinte:
    <NEXT_WEEK_CONTENT>{topic_of_the_week}</NEXT_WEEK_CONTENT>

  expected_output: >
    Um relatório com as informações mais relevantes que você encontrou, incluindo hashtags relevantes para o conteúdo desta semana e todas as outras informações que possam ser úteis para a equipe de criação de conteúdo.

content_strategy_development:
  description: >
    Com base nos resultados da pesquisa de mercado, desenvolva um calendário de conteúdo abrangente para uma semana. O calendário deve especificar o tema para cada dia da semana (de segunda a domingo) onde algum conteúdo deve ser postado, e ideias preliminares para o conteúdo da postagem. Por enquanto, concentre-se em um calendário de conteúdo de três dias, incluindo as palavras-chave e hashtags mais relevantes a serem usadas em cada postagem.

  expected_output: >
    Um calendário de conteúdo detalhado para a semana, formatado como markdown, que inclui os dias da semana (de segunda a sexta-feira), uma breve visão geral das ideias de conteúdo e as palavras-chave e hashtags mais relevantes a serem usadas em cada postagem. Garanta que o calendário esteja alinhado com as tendências identificadas e as preferências do público.

visual_content_creation:
  description: >
    Com base na estratégia de conteúdo para cada postagem no Instagram, crie a arte visual que será publicada no Instagram em cada dia da semana. Para isso, você precisará criar uma descrição detalhada da imagem que usará para cada dia. As descrições que você usará precisam ser detalhadas, mas concisas, e devem incluir os elementos principais que devem estar presentes na imagem. Descreva as cores, os objetos, o clima e qualquer outra informação relevante que você considere importante para a criação da imagem.

    Aqui estão alguns exemplos de descrições que você poderia usar:
    - Uma imagem realista de uma sala de estar com um design moderno. A sala deve ter uma grande janela com vista para uma paisagem urbana. A paleta de cores deve ser neutra, com um toque de cor na forma de um sofá vermelho. A sala deve ser bem iluminada, com uma atmosfera aconchegante e convidativa.
    - Uma imagem minimalista de uma escrivaninha com um laptop, um caderno e uma xícara de café. A escrivaninha deve ser de madeira clara, e o fundo deve ser uma parede branca lisa. A imagem deve transmitir uma sensação de foco e produtividade.
    - Uma imagem vibrante de uma praia tropical ao pôr do sol. A praia deve estar deserta, com palmeiras balançando ao vento. O céu deve ser uma mistura de cores quentes, com o sol se pondo no horizonte. A imagem deve evocar uma sensação de relaxamento e tranquilidade.

  expected_output: >
    Um documento em markdown com descrições detalhadas das imagens que serão usadas para cada postagem no Instagram da semana. Cada descrição deve ser concisa e incluir os elementos principais, cores, clima e qualquer outra informação relevante que guiará a criação da imagem. As descrições devem estar alinhadas com o calendário de conteúdo e as tendências identificadas.

copywriting:
  description: >
    Escreva copys cativantes, relevantes e em português para cada postagem no Instagram da semana, alinhadas aos temas estratégicos do calendário de conteúdo. A copy deve envolver o público, incorporar a voz da marca e incentivar a interação. A cópia também deve ser amigável para SEO e incorporar as palavras-chave e hashtags relevantes contidas no cronograma de conteúdo.

    Considere as seguintes diretrizes ao escrever a copy:
    - Mantenha a copy concisa e envolvente.
    - Inclua uma chamada para ação onde for apropriado.
    - Use palavras-chave e hashtags relevantes.
    - Garanta que a copy esteja alinhada com a voz e o tom da marca.

    Aqui estão alguns exemplos da copy que você poderia usar:
    - "Olá a todos! :heart: Estamos empolgados para compartilhar nossa última coleção com vocês. Confiram nosso site para mais detalhes. #novacoleção #moda #estilo"
    - "Feliz segunda-feira! :sunflower: Comece sua semana direito com nossos deliciosos smoothies. Visite nossa loja hoje! #smoothies #vidasaudável #motivaçãodesegunda"
    - "Está se sentindo estressado? :massage: Presenteie-se com um dia relaxante de spa. Reserve agora e desfrute do luxo. #diadespa #relaxamento #autocuidado"

  expected_output: >
    Um documento formatado como markdown, com várias seções. Cada seção deve conter a cópia para uma única postagem no Instagram, juntamente com as hashtags e chamadas para ação relevantes. A cópia deve ser envolvente, fiel à marca e alinhada ao calendário de conteúdo.

report_final_content_strategy:
  description: >
    Compile um relatório abrangente que descreve a estratégia de conteúdo final para a semana. O relatório deve incluir os resultados da pesquisa de mercado, o calendário de conteúdo, a cópia de cada postagem e as imagens geradas por IA. Forneça uma breve justificativa para a estratégia, explicando como ela se alinha com as tendências identificadas e as preferências do público.

  expected_output: >
    Um relatório detalhado que inclui os resultados da pesquisa de mercado, o calendário de conteúdo, a cópia de cada postagem e as imagens geradas por IA. O relatório deve ser formatado como markdown e incluir uma breve justificativa para a estratégia, explicando como ela se alinha com as tendências identificadas e as preferências do público.
